### ISSUE TITLE
Can't start the plugin

### ISSUE THREAD

**Issue by PestToast** [0xB10C/c-lightning-plugin-csvexportpays#1]
Trying to start the plugin, and the closest I can get is when I use
`plugin start /path/to/csvexportpays.py`
which returns:
`Traceback (most recent call last):
  File "/path/to/csvexportpays.py", line 25, in <module>
    from lightning import Plugin, LightningRpc
ModuleNotFoundError: No module named 'lightning'
{
   "code": -3,
   "message": "/path/to/csvexportpays.py: exited before replying to getmanifest"
}
`

**Comment by 0xB10C** [comment]
Hm, I haven't used or worked on this plugin in about two years. It's not maintained. I think the c-lightning plugin API might have changed. 

I'll close this issue and archive the project. Feel free to fork if you want to maintain a working version.
